CC=g++
CFLAGS=-I.

all: example1_1 example1_2 example1_3 example1_4 example1_5 example2_1 example3_1 example3_2 example3_3 example3_4 example3_5 example3_6 example3_7 example4_1 example4_2 example4_3 example4_4 example4_5 example4_6 example4_7 example4_8 example5_1 example5_2 example5_3 example5_4 example5_5 example5_6 example5_7 example5_8 example5_9 example5_10

example1_1: example1_1.cpp
	$(CC) -o example1_1 example1_1.cpp -I.

example1_2: example1_2.cpp
	$(CC) -o example1_2 example1_2.cpp -I.

example1_3: example1_3.cpp
	$(CC) -o example1_3 example1_3.cpp -I.

example1_4: example1_4.cpp
	$(CC) -o example1_4 example1_4.cpp -I.

example1_5: example1_5.cpp
	$(CC) -o example1_5 example1_5.cpp -I.

example2_1: example2_1.cpp
	$(CC) -o example2_1 example2_1.cpp -I.

example3_1: example3_1.cpp
	$(CC) -o example3_1 example3_1.cpp -I.

example3_2: example3_2.cpp
	$(CC) -o example3_2 example3_2.cpp -I.

example3_3: example3_3.cpp
	$(CC) -o example3_3 example3_3.cpp -I.

example3_4: example3_4.cpp
	$(CC) -o example3_4 example3_4.cpp -I.	

example3_5: example3_5.cpp
	$(CC) -o example3_5 example3_5.cpp -I.

example3_6: example3_6.cpp
	$(CC) -o example3_6 example3_6.cpp -I.
	
example3_7: example3_7.cpp
	$(CC) -o example3_7 example3_7.cpp -I.

example4_1: example4_1.cpp
	$(CC) -o example4_1 example4_1.cpp -I.

example4_2: example4_2.cpp
	$(CC) -o example4_2 example4_2.cpp -I.

example4_3: example4_3.cpp
	$(CC) -o example4_3 example4_3.cpp -I.

example4_4: example4_4.cpp
	$(CC) -o example4_4 example4_4.cpp -I.

example4_5: example4_5.cpp
	$(CC) -o example4_5 example4_5.cpp -I.

example4_6: example4_6.cpp
	$(CC) -o example4_6 example4_6.cpp -I.

example4_7: example4_7.cpp
	$(CC) -o example4_7 example4_7.cpp -I.

example4_8: example4_8.cpp
	$(CC) -o example4_8 example4_8.cpp -I.

example5_1: example5_1.cpp
	$(CC) -o example5_1 example5_1.cpp -I.

example5_2: example5_2.cpp
	$(CC) -o example5_2 example5_2.cpp -I.

example5_3: example5_3.cpp
	$(CC) -o example5_3 example5_3.cpp -I.

example5_4: example5_4.cpp
	$(CC) -o example5_4 example5_4.cpp -I.

example5_5: example5_5.cpp
	$(CC) -o example5_5 example5_5.cpp -I.

example5_6: example5_6.cpp
	$(CC) -o example5_6 example5_6.cpp -I.

example5_7: example5_7.cpp
	$(CC) -o example5_7 example5_7.cpp -I.

example5_8: example5_8.cpp
	$(CC) -o example5_8 example5_8.cpp -I.

example5_9: example5_9.cpp
	$(CC) -o example5_9 example5_9.cpp -I.

example5_10: example5_10.cpp
	$(CC) -o example5_10 example5_10.cpp -I.